### PR TITLE
Figure 1C

### PR DESCRIPTION
**Pull request by JustasB**

### CODE REVIEW

**Comment by pgleeson** [comment]
It's not quite there yet. The subthreshold behaviours are different:

selection_240

selection_241

 I suspect this may be down to the vtraub/VT parameter which is not reported in Fig2 (or tau max). 

You may be best to try to get matching between the Figs in paper & examples using the original scripts first before trying in NML2. See https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NEURON_MODIFIED/test_RS_Fig1c.hoc. Try writing such scripts for other figs & see if any match and work from there...

**Comment by JustasB** [comment]
For fig 1C, the original scripts do not match the figures (spikes or sub-thres) using the values included in the paper:

Not even close at 0.5 uA (as specified in 1C caption)
fig1c 0 5 ua

Closer at 0.7 uA (as used in 1A), but different number of spikes (13 vs 10 in figure)
fig1c 0 7 ua

What would you like me to try in regards to: "I suspect this may be down to the vtraub/VT parameter which is not reported in Fig2 (or tau max)."?

**Comment by pgleeson** [comment]
Looks like you've got the idea re vtraub with the last few commits. Are Figs 2/3/4 looking any better?

**Comment by JustasB** [comment]
Not really. The figs don't include current or timings, so I'm really just guessing. The sub-thres behavior is unchanged as well.

**Comment by pgleeson** [comment]
Merging and I'll take another look at it.

**Pull request merged**
